### ISSUE TITLE
vertex weights from sigma (NLF)

### ISSUE THREAD

**Issue by siyuzou** [isarandi/smplfitter#1]
Hi @isarandi ! Thanks for sharing this handful tool!

NLF predicts per-vertex sigmas, while smplfitter (optionally) takes in vertex weights. Could you pls share the conversion from sigmas to weights?

**Comment by isarandi** [comment]
Hi, thanks for the question. An exponent of -1.5 and normalizing to unit mean works well in my experience. 

```
w = u**-1.5
w /= mean(w, axis=-1, keepdims=True) 
```

**Comment by siyuzou** [comment]
Thanks!
